FROM centos
LABEL maintainer 'julio sarango <jsarangoq@gmail.com>'
#RUN yum -y install vim &&  yum -y install emacs     
RUN mkdir config 
RUN mkdir usuarios
ADD ./files/config /config/ 
ADD ./files/usuarios /usuarios/



